dist: bionic

language: python

# Don't bother with Python 2.
python:
  - '3.6'
  - '3.7'
  - '3.8'

# Test for compatibility with old pandas and numpy,
# using the versions currently in the Ubuntu repos.
env:
  - NUMPY=1.13.* PANDAS=0.22.*
  - NUMPY=1.* PANDAS=0.*

# Exclude incompatible combinations of versions
# (old libraries beyond Python 3.6).
jobs:
  exclude:
  - python: '3.7'
    env: NUMPY=1.13.* PANDAS=0.22.*
  - python: '3.8'
    env: NUMPY=1.13.* PANDAS=0.22.*

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install numpy==$NUMPY pandas==$PANDAS --force-reinstall
  - python setup.py bdist_wheel
  - pip install dist/saccades*.whl

# Don't waste time cloning previous commits.
# No git stuff is tested anyway.
git:
  depth: 1

branches:
  only:
  - master

# Run the tests and build the docs.
script:
  - pytest --cov=saccades --cov-report=xml --cov-report=term-missing
  - ./scripts/build_docs.sh

# Upload test coverage report.
after_success:
  - codecov
